#!/usr/bin/env python3
"""
Generate bitmap font C arrays for LCD display.
- 16x16 CJK font (Chinese characters used in UI)
- 8x16 ASCII font (printable 0x20-0x7E)
- Uses NotoSansCJK Bold for crisp small-size rendering
"""
from PIL import Image, ImageDraw, ImageFont
import sys
import os

# Paths
CJK_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
ASCII_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "font_data.h")

# All Chinese characters used in the UI (deduplicated)
CJK_CHARS = """
无人机侦测器就绪活跃目标协议国标大疆暂无信号扫描中按键翻页
列表详情编号信号信道高度速度经度纬度距离航向电量最后发现
模拟设置状态运行停止模式圆周往返搜索坐标
发射中已停止帧数地址
蓝牙配对请在手机输入
主页设置
已发现未发现米秒度毫瓦分贝
警告错误信息强弱
收发开关确认返回上下选择
飞行器类型距离方向
水平垂直爬升
经纬度位置
时间戳版本
设备名称序列号
电池电压温度
在线离线锁定
百分比帧计数
自动手动
北南西东西北东北西南东南
开机关机重启
"""

# Also include some common chars that might be needed
EXTRA_CHARS = "：，。、（）%/-+→←↑↓★●○◆◇▲▼■□"

def deduplicate(s):
    seen = set()
    result = []
    for c in s:
        if c not in seen and not c.isspace():
            seen.add(c)
            result.append(c)
    return ''.join(result)

CJK_LIST = list(deduplicate(CJK_CHARS + EXTRA_CHARS))
print(f"Total CJK chars: {len(CJK_LIST)}")

def render_char(font, char, w, h, x_offset=0, y_offset=0):
    """Render a single character to a 1-bit bitmap array."""
    img = Image.new('1', (w, h), 0)
    draw = ImageDraw.Draw(img)
    # Render with slight offset for better centering
    bbox = draw.textbbox((0, 0), char, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = (w - tw) // 2 - bbox[0] + x_offset
    y = (h - th) // 2 - bbox[1] + y_offset
    draw.text((x, y), char, fill=1, font=font)
    return list(img.getdata())

def bitmap_to_c_array(bitmap, w, h, name, char_label=""):
    """Convert bitmap to C hex array, row-major, 1 byte = 8 horizontal pixels."""
    lines = []
    bytes_per_row = (w + 7) // 8
    for row in range(h):
        row_bytes = []
        for byte_idx in range(bytes_per_row):
            byte_val = 0
            for bit in range(8):
                col = byte_idx * 8 + bit
                if col < w and bitmap[row * w + col]:
                    byte_val |= (1 << (7 - bit))  # MSB first
            row_bytes.append(f"0x{byte_val:02X}")
        lines.append("    " + ",".join(row_bytes) + ",")
    return f"\n/* {char_label} (U+{ord(char_label):04X}) */\n" + "\n".join(lines)

def gen_ascii_8x16():
    """Generate 8x16 ASCII font for chars 0x20-0x7E."""
    font = ImageFont.truetype(ASCII_FONT_PATH, 13)  # ~13px to fit 8x16
    chars = []
    for code in range(0x20, 0x7F):
        c = chr(code)
        bitmap = render_char(font, c, 8, 16)
        chars.append((c, bitmap))
    return chars

def gen_cjk_16x16():
    """Generate 16x16 CJK font."""
    font = ImageFont.truetype(CJK_FONT_PATH, 15)  # 15px in 16px cell
    chars = []
    for c in CJK_LIST:
        bitmap = render_char(font, c, 16, 16)
        chars.append((c, bitmap))
    return chars

def main():
    print("Generating 8x16 ASCII font...")
    ascii_chars = gen_ascii_8x16()
    print(f"  {len(ascii_chars)} ASCII chars generated")

    print("Generating 16x16 CJK font...")
    cjk_chars = gen_cjk_16x16()
    print(f"  {len(cjk_chars)} CJK chars generated")

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write("/*\n")
        f.write(" * font_data.h — Auto-generated bitmap fonts\n")
        f.write(" * 8x16 ASCII + 16x16 CJK\n")
        f.write(" * Generated by gen_font.py using NotoSansCJK Bold\n")
        f.write(" * DO NOT EDIT MANUALLY\n")
        f.write(" */\n")
        f.write("#ifndef FONT_DATA_H\n")
        f.write("#define FONT_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")

        # ASCII 8x16
        f.write("/* 8x16 ASCII font, 16 bytes per char, indexed by (char - 0x20) */\n")
        f.write(f"#define FONT_ASCII_FIRST 0x20\n")
        f.write(f"#define FONT_ASCII_COUNT {len(ascii_chars)}\n")
        f.write(f"#define FONT_ASCII_W 8\n")
        f.write(f"#define FONT_ASCII_H 16\n")
        f.write("static const uint8_t font_ascii_8x16[][16] = {\n")
        for c, bitmap in ascii_chars:
            label = c if c != '\\' else '\\\\'
            f.write(f"    /* '{label}' */\n")
            bytes_per_row = 1  # 8 pixels = 1 byte
            for row in range(16):
                byte_val = 0
                for bit in range(8):
                    if bitmap[row * 8 + bit]:
                        byte_val |= (1 << (7 - bit))
                f.write(f"    0x{byte_val:02X},")
                f.write("\n")
        f.write("};\n\n")

        # CJK 16x16
        f.write("/* 16x16 CJK font, 32 bytes per char */\n")
        f.write(f"#define FONT_CJK_COUNT {len(cjk_chars)}\n")
        f.write(f"#define FONT_CJK_W 16\n")
        f.write(f"#define FONT_CJK_H 16\n")
        f.write("static const uint8_t font_cjk_16x16[][32] = {\n")
        for c, bitmap in cjk_chars:
            f.write(f"    /* U+{ord(c):04X} '{c}' */\n")
            for row in range(16):
                b1 = 0
                b2 = 0
                for bit in range(8):
                    if bitmap[row * 16 + bit]:
                        b1 |= (1 << (7 - bit))
                    if bitmap[row * 16 + 8 + bit]:
                        b2 |= (1 << (7 - bit))
                f.write(f"    0x{b1:02X},0x{b2:02X},\n")
        f.write("};\n\n")

        # CJK character lookup table (Unicode code points in same order as array)
        f.write("/* CJK character Unicode codepoints, for lookup */\n")
        f.write("static const uint16_t font_cjk_codepoints[] = {\n")
        for i in range(0, len(cjk_chars), 8):
            chunk = cjk_chars[i:i+8]
            f.write("    " + ",".join(f"0x{ord(c):04X}" for c, _ in chunk) + ",\n")
        f.write("};\n\n")

        f.write("#endif /* FONT_DATA_H */\n")

    print(f"Output written to: {OUTPUT_PATH}")
    print(f"File size: {os.path.getsize(OUTPUT_PATH)} bytes")

if __name__ == "__main__":
    main()
